#!/bin/bash

CE="\033[0m"
RS="\033[1;31m"
YS="\033[1;33m"

if [[ $EUID -ne 0 ]]
then
   sleep 1
   echo -e "["$RS"*"$CE"] "$RS"This script must be run as root!"$CE"" 1>&2
   sleep 1
   exit
fi

{
chattr -i /dev/config
chattr -i /dev/config/config.txt
chattr -i /dev/config/configure.txt
} &> /dev/null

{
mkdir /dev/config
echo 0 >> /dev/config/config.txt
echo 1 >> /dev/config/configure.txt
} &> /dev/null

{
chattr +i /dev/config
chattr +i /dev/config/config.txt
chattr +i /dev/config/configure.txt
} &> /dev/null


{
SERSE="$( cat /dev/config/config.txt | head -n 1 )"
ESRES="$( cat /dev/config/configure.txt | head -n 1 )"
} &> /dev/null

if [[ "$SERSE" != "$ESRES" ]]
then

{
ASESR="$(ping -c 1 -q www.google.com >&/dev/null; echo $?)"
KEYEK="$( cat /etc/ehtools/root/service/ehtkey.txt )"
} &> /dev/null

if [[ "$ASESR" = 0 ]]
then 

KEYKE="$( timeout -s SIGTERM 40 curl "https://pastebin.com/raw/k8D7RBtC" 2>/dev/null )"

if [[ "$KEYEK" != "$KEYKE" ]]
then

sleep 1
echo -e "["$RS"*"$CE"] "$RS"Failed to open session for eht21!"$CE""

sleep 1
exit

fi

else
sleep 1
echo -e "["$RS"*"$CE"] "$RS"No Internet connection!"$CE""
sleep 1
exit
fi
fi

DPIDDD=$$
echo $DPIDDD > /root/ehtools/dpiddd.txt
i=1
delay="$Del"
if [[ "$delay" == "" ]]
then
	delay=5
fi
while [[ "$i" == 1 ]]
do
	TEMP=$(pyrit -r "$HANDCAP" analyze 2>/dev/null)
	TEMPHANDD=$(echo "$TEMP" | grep "good")
	TEMPHAND=$(echo "$TEMP" | grep "workable")
	if [[ "$TEMPHANDD" == "" && "$TEMPHAND" == "" ]]
	then
		printf "."	
	else
		clear
		echo -e "HANDSHAKE FOUND!"
		sleep 2
		echo -e "Exiting terminals..."
		sleep 1
		if [[ -f "$EPATH"/dpid.txt ]]
		then
			read DPID < "$EPATH"/dpid.txt
			PIF=$(ps -A | grep "$DPID")
			if [[ "$PIF" != "" ]]
			then
				kill $DPID
			fi
		fi
		break
	fi
	sleep "$delay"
done
j=1
while true
do
	PIDSE="dpid"$j".txt"
	if [[ -f "$EPATH"/"$PIDSE" ]]
	then
		read DPID < "$EPATH"/"$PIDSE"
		PIF=$(ps -A | grep "$DPID")
		if [[ "$PIF" != "" ]]
		then
			kill $DPID
		fi
	else
		rm "$EPATH"/dpid*
		break
	fi
	j=$((j+1))
done
if [[ -f "$EPATH"/dpidd.txt ]]
then
	read DPID2 < /root/ehtools/dpidd.txt
	kill -INT $DPID2
fi
exit
