#!/bin/bash

CE="\033[0m"
RS="\033[1;31m"
YS="\033[1;33m"

if [[ $EUID -ne 0 ]]
then
   sleep 1
   echo -e "["$RS"*"$CE"] "$RS"This script must be run as root!"$CE"" 1>&2
   sleep 1
   exit
fi

passcode="$(cat /root/ehtools/etc/.config)"
read -s -p $'Password: ' output
if [[ $output != $passcode ]]
then
	echo -e "libenc: Sorry"
else
{
CONF="$( cat /root/ehtools/etc/.config )"
cd /etc/ehtools
chattr -i /etc/ehtools
chattr -i /etc/ehtools/login
openssl enc -aes-256-cbc -pass pass:"$CONF" -p -in login -out login.enc -base64
rm login
mv login.enc login
chattr +i /etc/ehtools/login
chattr -i /etc/ehtools/password
openssl enc -aes-256-cbc -pass pass:"$CONF" -p -in password -out password.enc -base64
rm password
mv password.enc password
chattr +i /etc/ehtools/password
chattr -i /etc/ehtools/root
chattr -i /etc/ehtools/root/password
cd /etc/ehtools/root
openssl enc -aes-256-cbc -pass pass:"$CONF" -p -in password -out password.enc -base64
rm password
mv password.enc password
chattr +i /etc/ehtools/root/password
chattr +i /etc/ehtools/root
chattr +i /etc/ehtools
} &> /dev/null
fi
