#!/bin/bash

CE="\033[0m"
RS="\033[1;31m"
YS="\033[1;33m"

if [[ $EUID -ne 0 ]]
then
   sleep 1
   echo -e "["$RS"*"$CE"] "$RS"This script must be run as root!"$CE"" 1>&2
   sleep 1
   exit
fi

passcode="$(cat /root/ehtools/etc/.config)"
read -s -p $'Password: ' output
if [[ $output != $passcode ]]
then
	echo -e "libunchattr: Sorry"
else
{
chattr -i /bin/ehtools
chattr -i /etc/ehtools/ehtoold/ehtconsole
chattr -i /bin/epasswd
chattr -i /bin/ehtkey
chattr -i /bin/ehtmod
chattr -i /bin/ehtapp
chattr -i /etc/ehtools/login
chattr -i /etc/ehtools/password
chattr -i /etc/ehtools
chattr -i /etc/ehtools/root
chattr -i /etc/ehtools/root/password
} &> /dev/null
fi
