#!/bin/bash

CE="\033[0m"
RS="\033[1;31m"
YS="\033[1;33m"

if [[ $EUID -ne 0 ]]
then
   sleep 1
   echo -e "["$RS"*"$CE"] "$RS"This script must be run as root!"$CE"" 1>&2
   sleep 1
   exit
fi

passcode="$(cat /root/ehtools/etc/.config)"
read -s -p $'Password: ' output
if [[ $output != $passcode ]]
then
	echo -e "libunconf: Sorry"
else
{
chattr -i /etc/ehtools/.config
chattr -i /etc/ehtools
chattr -i /root/ehtools/etc
chattr -i /root/ehtools/etc/.config
} &> /dev/null
fi
