#!/bin/bash

CE="\033[0m"
RS="\033[1;31m"
YS="\033[1;33m"

if [[ $EUID -ne 0 ]]
then
   sleep 1
   echo -e "["$RS"*"$CE"] "$RS"This script must be run as root!"$CE"" 1>&2
   sleep 1
   exit
fi

cd /root
git clone https://github.com/LeonardoNve/dns2proxy
cd dns2proxy
python /root/dns2proxy/dns2proxy.py
read
